site_name: NFDI MatWerk Ontology
theme: readthedocs
nav:
  - Welcome: index.md
  - Introduction: intro.md
  - Ontology structure: ontology.md
  - Patterns and use cases: patterns.md
  - Versions: versions.md
  - Contributing: contributing.md
  - Acknowledgements: acknowledgements.md
  - References and publications: refefences.md