name: HTML

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        path: main
    - name: Build HTML for main
      run: |
           wget -O widoco.jar https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
           mkdir public
           java -jar widoco.jar -ontFile main/mwo.ttl -outFolder public -uniteSections -includeAnnotationProperties -lang en-de  -getOntologyMetadata -noPlaceHolderText -rewriteAll -webVowl
           ls public
           #echo -e "\n img { max-width:1000px }" >> public/doc/resources/extra.css
           #cat public/doc/resources/extra.css
           #mv public/doc/* public/
           cp public/index-en.html public/index.html
           cp -r public 3.0.0
           mv 3.0.0 public/


           pip install mkdocs
           cd main
           mkdocs build -f mkdocs.yaml

           cd ..
           mkdir public/docs
           cp -r main/site/* public/docs/

 
    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: documentation
        build_dir: public/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
